### ISSUE TITLE
How to use TwitterCore.framework

### ISSUE THREAD

**Issue by kakaluo** [touren/twitter-kit-ios#6]
I run ./build.sh and build TwitterKit.framwork successfully(I have changed to static library)，but I got many errors after importing TwitterKit.framwork and TwitterCore.framework(original).

### Expected behavior

Build my project  successfully.

### Actual behavior

Got many errors：
duplicate symbol '_OBJC_CLASS_$_TWTRUserAuthRequestSigner' in:
    /Users/myproject/framework/TwitterSDK/TwitterKit.framework/TwitterKit(TWTRUserAuthRequestSigner.o)
    /Users/myproject/framework/TwitterSDK/TwitterCore.framework/TwitterCore(TWTRUserAuthRequestSigner.o)
duplicate symbol '_OBJC_METACLASS_$_TWTRUserAuthRequestSigner' in:
    /Users/myproject/framework/TwitterSDK/TwitterKit.framework/TwitterKit(TWTRUserAuthRequestSigner.o)
    /Users/myproject/framework/TwitterSDK/TwitterCore.framework/TwitterCore(TWTRUserAuthRequestSigner.o)
duplicate symbol '_OBJC_CLASS_$_TWTRSecItemWrapper' in:
    /Users/myproject/framework/TwitterSDK/TwitterKit.framework/TwitterKit(TWTRSecItemWrapper.o)
    /Users/myproject/framework/TwitterSDK/TwitterCore.framework/TwitterCore(TWTRSecItemWrapper.o)

### Steps to reproduce the behavior

However, If I remove TwitterCore.framework(remove reference) the project run well. If I remove TwitterCore.framework in finder, it procuced 'TwitterCore/TwitterCore.h' file not found.

**Comment by touren** [comment]
The reason is, in the original project, both TwitterCore.framework and TwitterKit.framework are using the same static library TwitterCore.a.
Only use `pod 'TwitterKit5'`, it will include the `TwitterCore` and it could be build and run, although there will be a lot of warnings when you run the project.
Some workaround is here https://github.com/twitter-archive/twitter-kit-ios/issues/91


If you want to use your own TwitterKit.zip, you could
1. upload the TwitterKit.zip file somewhere and get a [URL](https://swarm-dev.s3.amazonaws.com/pods/twitterkit/ios/5.0.0/TwitterKit.zip) points to it.
2. Change your [podspec](https://raw.githubusercontent.com/touren/twitter-kit-ios/Swift5/TwitterKit/TwitterKit.podspec) file as: s.source = { :http => "<URL created in step 1>" }
3. Change your Podfile as: `pod "TwitterKit"` ==> `pod "TwitterKit", :podspec => "<URL point to the podspec created in step 2>"`

**Comment by kakaluo** [comment]
Thanks, everything is ok after removing TwitterCore.a in TwitterKit project！
